import type { StoryStep } from "../story.types";

export const failureReworkSteps: StoryStep[] = [
  {
    id: "telemetry",
    route: "/dashboard",
    target: "[data-story='trigger-telemetry']",
    title: "Controlled telemetry degradation",
    description: "Three observations enter the normal telemetry ingestion service. The critical sample starts the accepted recovery graph.",
    manualInstruction: "Select Trigger controlled telemetry.",
    mode: "system",
    action: { type: "trigger_telemetry" },
    evidence: { type: "active_case" },
  },
  {
    id: "prediction",
    route: "/failure",
    target: "[data-story='failure-prediction']",
    title: "Controlled prediction and failure alert",
    description: "The persisted prediction flags thermal runaway and bearing degradation on WS-102.",
    manualInstruction: "Open the active failure evidence.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "allocation-lock",
    route: "/failure",
    target: "[data-story='allocation-lock']",
    title: "Allocation lock active",
    description: "Workstation WS-102 is immediately isolated with an active allocation lock to prevent new job dispatch.",
    manualInstruction: "Inspect the active allocation lock.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "maintenance-start",
    route: "/maintenance",
    target: "[data-story='maintenance-start']",
    title: "Start maintenance",
    description: "An authorized command moves the machine into maintenance execution.",
    manualInstruction: "Select Start Maintenance.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "start_maintenance", workOrderId: "WO-WS102-081", expectedStage: 2 },
    },
    evidence: { type: "maintenance_stage", min: 3 },
  },
  {
    id: "repair",
    route: "/maintenance",
    target: "[data-story='repair-complete']",
    title: "Record repair",
    description: "The bearing repair is persisted against the accepted work order.",
    manualInstruction: "Select Record Repair Complete.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "record_repair_completion", workOrderId: "WO-WS102-081", expectedStage: 3, notes: "Bearing replaced" },
    },
    evidence: { type: "maintenance_stage", min: 4 },
  },
  {
    id: "testing",
    route: "/maintenance",
    target: "[data-story='machine-testing']",
    title: "Machine testing",
    description: "Return-to-service testing begins while the allocation lock remains active.",
    manualInstruction: "Select Start Machine Testing.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "start_machine_testing", workOrderId: "WO-WS102-081", expectedStage: 4 },
    },
    evidence: { type: "maintenance_stage", min: 5 },
  },
  {
    id: "validation-fail",
    route: "/maintenance",
    target: "[data-story='validation-fail']",
    title: "Safety validation fails",
    description: "The intentional failure keeps WS-102 locked and records REQUIRES_INTERVENTION.",
    manualInstruction: "Select Validation FAIL.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "record_return_to_service_validation", workOrderId: "WO-WS102-081", expectedStage: 5, passed: false, notes: "Controlled validation fail" },
    },
    evidence: { type: "validation_failed" },
  },
  {
    id: "rework",
    route: "/maintenance",
    target: "[data-story='repair-complete']",
    title: "Corrective rework",
    description: "The technician records corrective rework through the same protected route.",
    manualInstruction: "Select Record Repair Complete again.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "record_repair_completion", workOrderId: "WO-WS102-081", expectedStage: 3, notes: "Corrective rework completed" },
    },
    evidence: { type: "maintenance_stage", min: 4 },
  },
  {
    id: "retest",
    route: "/maintenance",
    target: "[data-story='machine-testing']",
    title: "Retest",
    description: "The machine is tested again after rework.",
    manualInstruction: "Select Start Machine Testing.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "start_machine_testing", workOrderId: "WO-WS102-081", expectedStage: 4 },
    },
    evidence: { type: "maintenance_stage", min: 5 },
  },
  {
    id: "validation-pass",
    route: "/maintenance",
    target: "[data-story='validation-pass']",
    title: "Return to service",
    description: "A passing validation completes the work order, releases the lock, restores OPERATIONAL, and persists RECOVERED.",
    manualInstruction: "Select Validation PASS.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "record_return_to_service_validation", workOrderId: "WO-WS102-081", expectedStage: 5, passed: true, notes: "Passed validation" },
    },
    evidence: { type: "workflow_recovered" },
  },
  {
    id: "recovered",
    route: "/dashboard",
    target: "[data-story='recovered']",
    title: "Full recovery verified",
    description: "All systems operational. The allocation lock is released and plant throughput is restored.",
    manualInstruction: "Review the restored operational KPIs on the overview dashboard.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
];
