import type { StoryStep } from "../story.types";

export const goldenSteps: StoryStep[] = [
  {
    id: "telemetry",
    route: "/dashboard",
    target: "[data-story='trigger-telemetry']",
    title: "Controlled telemetry degradation",
    description: "Three observations enter the normal telemetry ingestion service. The critical sample starts the accepted recovery graph.",
    manualInstruction: "Select Trigger controlled telemetry.",
    mode: "system",
    action: { type: "trigger_telemetry" },
    evidence: { type: "active_case" },
  },
  {
    id: "prediction",
    route: "/failure",
    target: "[data-story='failure-prediction']",
    title: "Controlled prediction and allocation lock",
    description: "The persisted prediction identifies BRG-10023, applies the workstation lock, and flags affected jobs.",
    manualInstruction: "Open the active failure evidence.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "inventory",
    route: "/warehouse",
    target: "[data-story='inventory-result']",
    title: "Inventory branch",
    description: "The resource recovery agent inspects inventory and records that stock is unavailable, requiring vendor procurement.",
    manualInstruction: "Review the inventory branch.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "procurement",
    route: "/procurement",
    target: "[data-story='procurement-result']",
    title: "Vendor selection",
    description: "When stock is unavailable, approved vendors are ranked and a request plus queued notification are persisted.",
    manualInstruction: "Review the procurement handoff.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "reroute",
    route: "/rerouting",
    target: "[data-story='reroute-result']",
    title: "Production rerouting",
    description: "Capability, tooling, skill, lock, and projected capacity drive real persisted reroute decisions.",
    manualInstruction: "Inspect affected jobs and targets.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "approve-reroute",
    route: "/rerouting",
    target: "[data-story='approve-reroute']",
    title: "Approve reroute plan",
    description: "Authorize the reroute plan to divert scheduled jobs to alternative workstations.",
    manualInstruction: "Approve the proposed reroute plan.",
    mode: "action",
    action: { type: "workflow", command: { type: "approve_reroute" } },
    evidence: { type: "reroute_approved" },
  },
  {
    id: "shipment",
    route: "/shipment",
    target: "[data-story='shipment-impact']",
    title: "Delivery impact",
    description: "Shipment commitments are recalculated from recovery and reroute evidence.",
    manualInstruction: "Pan, zoom, fit the route, or select an affected shipment.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "notifications",
    route: "/notifications",
    target: "[data-story='notification-result']",
    title: "Stakeholder notification",
    description: "In-app notifications and delivery attempts are persisted; no external delivery is claimed.",
    manualInstruction: "Review the stakeholder audit state.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "maintenance-start",
    route: "/maintenance",
    target: "[data-story='maintenance-start']",
    title: "Start maintenance",
    description: "An authorized command moves the machine into maintenance execution.",
    manualInstruction: "Select Start Maintenance.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "start_maintenance", workOrderId: "WO-WS102-081", expectedStage: 2 },
    },
    evidence: { type: "maintenance_stage", min: 3 },
  },
  {
    id: "repair",
    route: "/maintenance",
    target: "[data-story='repair-complete']",
    title: "Record repair",
    description: "The bearing repair is persisted against the accepted work order.",
    manualInstruction: "Select Record Repair Complete.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "record_repair_completion", workOrderId: "WO-WS102-081", expectedStage: 3, notes: "Bearing replaced" },
    },
    evidence: { type: "maintenance_stage", min: 4 },
  },
  {
    id: "testing",
    route: "/maintenance",
    target: "[data-story='machine-testing']",
    title: "Machine testing",
    description: "Return-to-service testing begins while the allocation lock remains active.",
    manualInstruction: "Select Start Machine Testing.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "start_machine_testing", workOrderId: "WO-WS102-081", expectedStage: 4 },
    },
    evidence: { type: "maintenance_stage", min: 5 },
  },
  {
    id: "validation-fail",
    route: "/maintenance",
    target: "[data-story='validation-fail']",
    title: "Safety validation fails",
    description: "The intentional failure keeps WS-102 locked and records REQUIRES_INTERVENTION.",
    manualInstruction: "Select Validation FAIL.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "record_return_to_service_validation", workOrderId: "WO-WS102-081", expectedStage: 5, passed: false, notes: "Controlled validation fail" },
    },
    evidence: { type: "validation_failed" },
  },
  {
    id: "rework",
    route: "/maintenance",
    target: "[data-story='repair-complete']",
    title: "Corrective rework",
    description: "The technician records corrective rework through the same protected route.",
    manualInstruction: "Select Record Repair Complete again.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "record_repair_completion", workOrderId: "WO-WS102-081", expectedStage: 3, notes: "Corrective rework completed" },
    },
    evidence: { type: "maintenance_stage", min: 4 },
  },
  {
    id: "retest",
    route: "/maintenance",
    target: "[data-story='machine-testing']",
    title: "Retest",
    description: "The machine is tested again after rework.",
    manualInstruction: "Select Start Machine Testing.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "start_machine_testing", workOrderId: "WO-WS102-081", expectedStage: 4 },
    },
    evidence: { type: "maintenance_stage", min: 5 },
  },
  {
    id: "validation-pass",
    route: "/maintenance",
    target: "[data-story='validation-pass']",
    title: "Return to service",
    description: "A passing validation completes the work order, releases the lock, restores OPERATIONAL, and persists RECOVERED.",
    manualInstruction: "Select Validation PASS.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "record_return_to_service_validation", workOrderId: "WO-WS102-081", expectedStage: 5, passed: true, notes: "Passed validation" },
    },
    evidence: { type: "workflow_recovered" },
  },
  {
    id: "recovered",
    route: "/dashboard",
    target: "[data-story='recovered']",
    title: "Full recovery verified",
    description: "All systems operational. The allocation lock is released and plant throughput is restored.",
    manualInstruction: "Review the restored operational KPIs on the overview dashboard.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
];
