import type { StoryStep } from "../story.types";

export const localSpareSteps: StoryStep[] = [
  {
    id: "telemetry",
    route: "/dashboard",
    target: "[data-story='trigger-telemetry']",
    title: "Controlled telemetry degradation",
    description: "Three observations enter the normal telemetry ingestion service. The critical sample starts the accepted recovery graph.",
    manualInstruction: "Select Trigger controlled telemetry.",
    mode: "system",
    action: { type: "trigger_telemetry" },
    evidence: { type: "active_case" },
  },
  {
    id: "prediction",
    route: "/failure",
    target: "[data-story='failure-prediction']",
    title: "Controlled prediction and allocation lock",
    description: "The persisted prediction identifies BRG-10023, applies the workstation lock, and flags affected jobs.",
    manualInstruction: "Open the active failure evidence.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "inventory",
    route: "/warehouse",
    target: "[data-story='inventory-result']",
    title: "Local inventory available",
    description: "The resource recovery agent verifies that replacement bearings are in stock locally at the plant warehouse.",
    manualInstruction: "Review the available warehouse stock.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "reserve-bearing",
    route: "/warehouse",
    target: "[data-story='reserve-bearing']",
    title: "Initiate bearing reservation",
    description: "Open the stock reservation dialog to link a local bearing to the active work order.",
    manualInstruction: "Click Reserve 1 bearing.",
    mode: "action",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "reserve-bearing-confirm",
    route: "/warehouse",
    target: "[data-story='reserve-bearing-confirm']",
    title: "Confirm spare reservation",
    description: "Atomically allocate the physical bearing from bin B-04 to work order WO-WS102-081.",
    manualInstruction: "Click Confirm reservation.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "reserve_part", quantity: 1 },
    },
    evidence: { type: "bearing_reserved" },
  },
  {
    id: "reroute",
    route: "/rerouting",
    target: "[data-story='reroute-result']",
    title: "Production rerouting",
    description: "Capability, tooling, skill, lock, and projected capacity drive real persisted reroute decisions.",
    manualInstruction: "Inspect affected jobs and targets.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "approve-reroute",
    route: "/rerouting",
    target: "[data-story='approve-reroute']",
    title: "Approve reroute plan",
    description: "Authorize the reroute plan to divert scheduled jobs to alternative workstations.",
    manualInstruction: "Approve the proposed reroute plan.",
    mode: "action",
    action: { type: "workflow", command: { type: "approve_reroute" } },
    evidence: { type: "reroute_approved" },
  },
  {
    id: "shipment",
    route: "/shipment",
    target: "[data-story='shipment-impact']",
    title: "Delivery impact",
    description: "Shipment commitments are recalculated from recovery and reroute evidence.",
    manualInstruction: "Pan, zoom, fit the route, or select an affected shipment.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "notifications",
    route: "/notifications",
    target: "[data-story='notification-result']",
    title: "Stakeholder notification",
    description: "In-app notifications and delivery attempts are persisted; no external delivery is claimed.",
    manualInstruction: "Review the stakeholder audit state.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
  {
    id: "maintenance-start",
    route: "/maintenance",
    target: "[data-story='maintenance-start']",
    title: "Start maintenance",
    description: "An authorized command moves the machine into maintenance execution.",
    manualInstruction: "Select Start Maintenance.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "start_maintenance", workOrderId: "WO-WS102-081", expectedStage: 2 },
    },
    evidence: { type: "maintenance_stage", min: 3 },
  },
  {
    id: "repair",
    route: "/maintenance",
    target: "[data-story='repair-complete']",
    title: "Record repair",
    description: "The bearing repair is persisted against the accepted work order.",
    manualInstruction: "Select Record Repair Complete.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "record_repair_completion", workOrderId: "WO-WS102-081", expectedStage: 3, notes: "Bearing replaced" },
    },
    evidence: { type: "maintenance_stage", min: 4 },
  },
  {
    id: "testing",
    route: "/maintenance",
    target: "[data-story='machine-testing']",
    title: "Machine testing",
    description: "Return-to-service testing begins while the allocation lock remains active.",
    manualInstruction: "Select Start Machine Testing.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "start_machine_testing", workOrderId: "WO-WS102-081", expectedStage: 4 },
    },
    evidence: { type: "maintenance_stage", min: 5 },
  },
  {
    id: "validation-pass",
    route: "/maintenance",
    target: "[data-story='validation-pass']",
    title: "Return to service",
    description: "A passing validation completes the work order, releases the lock, restores OPERATIONAL, and persists RECOVERED.",
    manualInstruction: "Select Validation PASS.",
    mode: "action",
    action: {
      type: "workflow",
      command: { type: "record_return_to_service_validation", workOrderId: "WO-WS102-081", expectedStage: 5, passed: true, notes: "Passed validation" },
    },
    evidence: { type: "workflow_recovered" },
  },
  {
    id: "recovered",
    route: "/dashboard",
    target: "[data-story='recovered']",
    title: "Full recovery verified",
    description: "All systems operational. The allocation lock is released and plant throughput is restored.",
    manualInstruction: "Review the restored operational KPIs on the overview dashboard.",
    mode: "observe",
    action: { type: "none" },
    evidence: { type: "none" },
  },
];
