"use client";
import { useMemo, useState } from "react";
import type { Workstation } from "@/demo-data/workstations";
import { useOperations } from "@/contexts/OperationsContext";

type Metric = { powerKw: number; oeePercent: number; cycleTimeSeconds: number; outputPerHour: number; defectRatePercent: number; estimatedRulDays: number; operatorId: string; firmwareVersion: string; networkPingMs: number; lastMaintenanceAt: string; nextMaintenanceAt: string };
type Telemetry = { temperature: number; vibration: number; anomalySeverity: string };
const headers = ["WS ID", "Type", "Status", "Temp (C)", "Vib (mm/s)", "Power (kW)", "OEE (%)", "Cycle Time (s)", "Output/hr", "Defect Rate (%)", "Last Maint.", "Next Maint.", "Est. RUL (Days)", "Operator ID", "Firmware", "Network Ping (ms)", "Anomaly Score", "Action"];
const dash = "—";

export function FunctionalHealthTable({ workstations, onOpenStation }: { workstations: readonly Workstation[]; onOpenStation: (id: string) => void }) {
  const { overview } = useOperations(); const [atRiskOnly, setAtRiskOnly] = useState(false);
  const latest = new Map((overview?.workstations ?? []).map((station) => { const item = station as typeof station & { telemetry?: Telemetry | null; metrics?: Metric | null }; return [station.code, item]; }));
  const rows = useMemo(() => workstations.filter((station) => !atRiskOnly || station.status === "At Risk"), [atRiskOnly, workstations]);
  const valuesFor = (station: Workstation) => { const item = latest.get(station.id); const t = item?.telemetry; const m = item?.metrics; const type = station.name.includes("Robot") ? "Robotic Arm" : station.name.includes("Conveyor") ? "Conveyor" : "CNC"; return [station.id, type, station.status, t?.temperature.toFixed(1) ?? dash, t?.vibration.toFixed(2) ?? dash, m?.powerKw.toFixed(1) ?? dash, m?.oeePercent.toFixed(1) ?? dash, m?.cycleTimeSeconds.toFixed(1) ?? dash, m?.outputPerHour ?? dash, m?.defectRatePercent.toFixed(2) ?? dash, m ? new Date(m.lastMaintenanceAt).toLocaleDateString() : dash, m ? new Date(m.nextMaintenanceAt).toLocaleDateString() : dash, m?.estimatedRulDays ?? dash, m?.operatorId ?? dash, m?.firmwareVersion ?? dash, m?.networkPingMs ?? dash, t?.anomalySeverity ?? dash]; };
  const exportCsv = () => { const lines = rows.map((station) => valuesFor(station).map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")); const blob = new Blob([[headers.slice(0, -1).join(","), ...lines].join("\n")], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `workstation-health-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); };
  return <section className="mt-10 overflow-hidden rounded-[2rem] bg-white p-6 shadow-[0_20px_40px_rgba(0,0,0,0.02)] sm:p-8"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><h2 className="text-xl font-semibold">Comprehensive Workstation Health Data</h2><div className="flex shrink-0 gap-2"><button type="button" onClick={() => setAtRiskOnly((value) => !value)} className="rounded-full bg-[#f7f3f2] px-4 py-2 text-xs font-semibold">{atRiskOnly ? "Show all" : "Filter at-risk"}</button><button type="button" onClick={exportCsv} className="rounded-full bg-[#f7f3f2] px-4 py-2 text-xs font-semibold">Export CSV</button></div></div><div className="overflow-x-auto rounded-xl border border-black/10"><table className="w-full min-w-[1700px] whitespace-nowrap text-left text-sm"><thead className="border-b border-black/15 text-[10px] font-semibold"><tr>{headers.map((header) => <th className="p-3" key={header}>{header}</th>)}</tr></thead><tbody className="divide-y divide-black/10">{rows.map((station) => <tr key={station.id}>{valuesFor(station).map((value, index) => <td className="p-3" key={`${station.id}-${index}`}>{value}</td>)}<td className="p-3"><button type="button" onClick={() => onOpenStation(station.id)} className="font-semibold underline">Inspect</button></td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-[#66636a]">Showing {rows.length} of {workstations.length} workstations. Metrics are simulated from the latest persisted telemetry snapshot.</p></section>;
}
