"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { ArrowRight, CheckCircle2, Mail } from "lucide-react";
import { Button } from "@/components/ui/button";

type AuthMode = "sign-in" | "sign-up" | "forgot-password" | "check-email";
export function AuthScreen({ mode }: { mode: AuthMode }) {
  const [submitted, setSubmitted] = useState(mode === "check-email"); const [email, setEmail] = useState(""); const [error, setError] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!email.includes("@")) { setError("Enter a valid email address."); return; } setError(""); if (mode === "sign-in") { const destination = new URLSearchParams(window.location.search).get("next"); window.location.assign(destination?.startsWith("/") ? destination : "/dashboard"); return; } setSubmitted(true); };
  const title = mode === "sign-in" ? "Open the controlled demo." : mode === "sign-up" ? "Create a demo workspace." : mode === "forgot-password" ? "Reset your demo access." : "Check your inbox.";
  if (submitted && mode !== "sign-in") return <AuthFrame title={title}><CheckCircle2 className="size-8 text-success" /><p className="mt-4 text-sm leading-6 text-muted-foreground">{mode === "sign-up" ? "Your demo workspace is ready. No plant, ERP, or equipment connection was created." : "If an account matches this email, a demo-only link has been prepared. No external email is sent by this controlled scenario."}</p><div className="mt-6 flex gap-3"><Button asChild><Link href={mode === "sign-up" ? "/onboarding" : "/sign-in"}>Continue <ArrowRight data-icon="inline-end" /></Link></Button><Button variant="outline" onClick={() => setSubmitted(false)}>Resend</Button></div></AuthFrame>;
  return <AuthFrame title={title}><p className="text-sm leading-6 text-muted-foreground">Demo authentication models role-aware access only. It does not represent production identity management.</p><form className="mt-6 flex flex-col gap-4" onSubmit={submit}><label className="flex flex-col gap-2 text-sm font-medium">Email address<input aria-invalid={Boolean(error)} value={email} onChange={(event) => setEmail(event.target.value)} type="email" autoComplete="email" className="h-11 rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" placeholder="name@example.com" /></label>{mode !== "forgot-password" ? <label className="flex flex-col gap-2 text-sm font-medium">Password<input type="password" minLength={8} autoComplete={mode === "sign-up" ? "new-password" : "current-password"} className="h-11 rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" placeholder="At least 8 characters" /></label> : null}{mode === "sign-up" ? <label className="flex items-start gap-2 text-sm text-muted-foreground"><input type="checkbox" required className="mt-1" />I understand this creates a demo workspace only.</label> : null}{error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}<Button type="submit">{mode === "sign-in" ? "Enter demo" : mode === "sign-up" ? "Create demo workspace" : "Request demo link"}<ArrowRight data-icon="inline-end" /></Button></form><div className="mt-5 flex flex-wrap gap-3 text-sm"><Link className="underline-offset-4 hover:underline" href={mode === "sign-in" ? "/forgot-password" : "/sign-in"}>{mode === "sign-in" ? "Forgot password?" : "Back to sign in"}</Link>{mode === "sign-in" ? <Link className="underline-offset-4 hover:underline" href="/sign-up">Create demo workspace</Link> : null}</div></AuthFrame>;
}
function AuthFrame({ title, children }: { title: string; children: React.ReactNode }) { return <main className="grid min-h-screen place-items-center bg-muted p-5"><section className="w-full max-w-md rounded-2xl border border-border bg-card p-7 shadow-sm"><Link href="/" className="flex items-center gap-2 font-heading text-sm font-semibold"><span className="flex size-7 items-center justify-center rounded-md bg-primary text-xs text-primary-foreground">MO</span>Machine Overwatch</Link><p className="mt-8 font-mono text-xs tracking-widest text-muted-foreground">DEMO ACCESS</p><h1 className="mt-3 font-heading text-3xl font-semibold tracking-[-0.04em]">{title}</h1>{children}<p className="mt-8 flex items-center gap-2 text-xs text-muted-foreground"><Mail className="size-3" /> Simulated identity and communication flow.</p></section></main>; }
