"use client";

import { Check, ChevronDown, Factory, Gauge, Route, ShieldCheck, TriangleAlert } from "lucide-react";
import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { OperationalPath } from "@/components/OperationalPath";
import { demoReroutingAlternatives, demoReroutingJobs } from "@/demo-data/ws102-scenario";
import { useOperations } from "@/contexts/OperationsContext";
import { cn } from "@/lib/utils";

export function ReroutingControl() {
  const { state, update } = useOperations();
  const [expandedJob, setExpandedJob] = useState("J1001");
  const selected = state.rerouteTargetId;
  const approved = state.routingApproved;
  const selectTarget = (target: string) => update({ rerouteTargetId: target, routingApproved: false, routingOutcome: "draft" });
  const approveAll = () => update({ routingApproved: !approved, routingOutcome: approved ? "draft" : "approved" });

  return <main className="min-h-screen bg-background px-5 py-8 text-[#1c1b1b] lg:px-8"><div className="mx-auto w-full max-w-[1440px] lg:pl-10">
    <header className="mb-10"><div className="flex flex-wrap items-center gap-3"><Badge variant="outline">DEMO DATA</Badge><span className="text-sm text-[#625e61]">Predictive Workstation Failure Detection</span></div><div className="mt-5 flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex flex-wrap items-center gap-3"><span className="inline-flex items-center gap-2 rounded-full bg-[#ffdad6] px-4 py-2 text-sm font-semibold text-[#ba1a1a]"><TriangleAlert className="size-4" />WS-102 High Failure Risk</span><span className="text-sm text-[#625e61]">Predicted in 18h</span></div><h1 className="mt-4 text-[32px] font-semibold tracking-[-0.025em]">Production Re-Routing Analysis</h1><p className="mt-2 text-base text-[#625e61]">Which jobs are affected on WS-102, and where should they go instead?</p></div><button onClick={approveAll} className="inline-flex min-h-14 items-center justify-center gap-2 rounded-full bg-black px-7 text-sm font-bold text-white shadow-md transition-colors hover:bg-[#303030]"><Route className="size-4" />{approved ? "Routing Plan Approved" : "Execute All Reroutes"}</button></div></header>

    <section className="grid items-start gap-6 xl:grid-cols-[1.28fr_0.92fr]">
      <section className="overflow-hidden rounded-[2rem] border border-[#ddd6ce] bg-[#fdfafa] shadow-[0_22px_40px_rgba(0,0,0,0.035)]"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-[#ded8d1] bg-white px-7 py-6"><h2 className="flex items-center gap-3 text-xl font-semibold"><Factory className="size-5 text-[#ba1a1a]" />Affected Jobs on WS-102</h2><span className="rounded-full bg-[#efebe7] px-3 py-1.5 text-xs font-semibold tracking-[0.05em] text-[#5f5a5d]">3 JOBS PENDING</span></div><div className="space-y-4 p-6">{demoReroutingJobs.map((job, index) => <RerouteJob key={job.id} job={job} index={index} expanded={expandedJob === job.id} selectedTarget={job.id === "J1003" ? "WS-108" : selected} approved={approved} onToggle={() => setExpandedJob((current) => current === job.id ? "" : job.id)} onSelectTarget={selectTarget} />)}</div></section>

      <div className="flex min-w-0 flex-col gap-6"><section className="relative overflow-hidden rounded-[2rem] border border-[#ddd6ce] bg-white p-7 shadow-[0_22px_40px_rgba(0,0,0,0.035)]"><div className="pointer-events-none absolute -right-16 -top-16 size-48 rounded-full bg-[#f5f1ed]" /><p className="relative text-xs font-semibold tracking-[0.06em] text-[#5d595d]">REROUTING IMPACT SUMMARY</p><div className="relative mt-6 grid grid-cols-2 gap-6"><SummaryNumber value={approved ? "0" : "0"} label="SLA Breaches" tone="success" /><SummaryNumber value="32%" label="Avg Utilization Inc." tone="warning" /></div></section><LoadDistribution selectedTarget={selected} /><section className="rounded-[2rem] border border-[#ddd6ce] bg-[#313030] p-6 text-white shadow-[0_22px_40px_rgba(0,0,0,0.08)]"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-emerald-400" /><div><h2 className="font-semibold">Controlled routing decision</h2><p className="mt-1 text-sm text-white/65">{approved ? "Approved in the demo workflow. Dispatch still requires a human release." : "Review capacity and confirm each job before execution."}</p></div></div></section></div>
    </section>

    <section className="mt-8"><OperationalPath title="Decision checks" description="The selected route remains a recommendation until an authorized user approves it." steps={[{ id: "capacity", label: "Capacity verified", detail: `${selected} retains enough scheduled capacity for the held work.`, state: "complete" }, { id: "capability", label: "Capability reviewed", detail: "Tooling, skill match, and priority remain visible to the scheduler.", state: "complete" }, { id: "approval", label: "Routing approval", detail: approved ? "The controlled routing plan is recorded as approved." : "Awaiting an authorized routing decision.", state: approved ? "complete" : "active" }, { id: "dispatch", label: "Dispatch release", detail: "No schedule dispatch is sent by this demonstration interface.", state: "upcoming" }]} /></section>
  </div></main>;
}

function RerouteJob({ job, index, expanded, selectedTarget, approved, onToggle, onSelectTarget }: { job: (typeof demoReroutingJobs)[number]; index: number; expanded: boolean; selectedTarget: string; approved: boolean; onToggle: () => void; onSelectTarget: (target: string) => void }) {
  const priority = index === 0 ? { label: "High", color: "bg-[#ffdad6] text-[#ba1a1a]", bar: "bg-[#ff4d56]" } : index === 1 ? { label: "Medium", color: "bg-[#fff0c8] text-[#946400]", bar: "bg-amber-400" } : { label: "Low", color: "bg-[#e6e4e5] text-[#514f50]", bar: "bg-[#4968ef]" };
  return <article className={cn("overflow-hidden rounded-[1.7rem] border bg-white transition-shadow", expanded ? "border-black shadow-[0_12px_24px_rgba(0,0,0,0.06)]" : "border-[#ddd6ce]")}><button onClick={onToggle} aria-expanded={expanded} className="flex w-full flex-wrap items-center gap-x-6 gap-y-4 px-6 py-5 text-left"><i className={cn("h-12 w-1 rounded-full", priority.bar)} /><div className="min-w-28 flex-1"><strong className="block font-mono text-xl">{job.id}</strong><span className="mt-1 block text-sm text-[#615d60]">{job.operation}</span></div><div><span className="block text-[10px] font-semibold tracking-[0.06em] text-[#656165]">PRIORITY</span><span className={cn("mt-2 inline-flex rounded-full px-2 py-1 text-xs font-semibold", priority.color)}>{priority.label}</span></div><div><span className="block text-[10px] font-semibold tracking-[0.06em] text-[#656165]">ORIGINAL CMT</span><strong className="mt-2 block text-sm">{index === 0 ? "Today, 14:00" : index === 1 ? "Tomorrow, 09:00" : "Tomorrow, 16:30"}</strong></div><span className={cn("ml-auto inline-flex items-center gap-2 rounded-full border px-3 py-2 text-sm", approved ? "border-emerald-700 bg-emerald-50 text-emerald-700" : expanded ? "border-black bg-[#efebe7]" : "border-[#ded8d1] text-[#5e595d]")}>{approved ? <Check className="size-4" /> : null}{approved ? "Approved" : expanded ? "Reviewing" : "Pending"}<ChevronDown className={cn("size-4 transition-transform", expanded && "rotate-180")} /></span></button>{expanded && <div className="border-t border-[#ded8d1] bg-[#efebe7] p-6"><p className="text-xs font-semibold tracking-[0.06em] text-[#5a5659]">SYSTEM RECOMMENDATION</p><div className="mt-4 grid gap-4 rounded-[1.5rem] bg-white p-5 shadow-sm lg:grid-cols-[118px_1fr_auto]"><div className="grid place-items-center rounded-2xl bg-[#f3f0ed] p-4 text-center"><Factory className="size-7" /><strong className="mt-3 block font-mono text-lg">{selectedTarget}</strong><span className="mt-1 text-xs text-emerald-700">Available</span></div><div className="grid gap-3 sm:grid-cols-2"><CheckItem label="Capacity" detail="+2h buffer available" /><CheckItem label="Skill Match" detail="Operator certified" /><CheckItem label="Tooling" detail="Requires 15m changeover" warning /><CheckItem label="Priority" detail="Meets SLA" /></div><div className="flex flex-row gap-2 lg:flex-col"><button onClick={() => onSelectTarget(selectedTarget === "WS-105" ? "WS-108" : "WS-105")} className="flex-1 rounded-xl border border-[#d7d1cc] px-4 py-3 text-sm font-semibold hover:bg-[#f6f3ef]">Edit Target</button><button onClick={() => onToggle()} className="flex-1 rounded-xl bg-black px-4 py-3 text-sm font-semibold text-white hover:bg-[#303030]">Confirm</button></div></div></div>}</article>;
}

function CheckItem({ label, detail, warning = false }: { label: string; detail: string; warning?: boolean }) { return <div className="flex items-start gap-2"><span className={cn("mt-1 grid size-5 shrink-0 place-items-center rounded-full", warning ? "bg-[#fff0c8] text-[#946400]" : "bg-emerald-100 text-emerald-700")}><Check className="size-3" /></span><span><strong className="block text-sm">{label}</strong><small className="block text-sm text-[#625e61]">{detail}</small></span></div>; }
function SummaryNumber({ value, label, tone }: { value: string; label: string; tone: "success" | "warning" }) { return <div><strong className="block text-5xl font-semibold tracking-[-0.05em]">{value}</strong><span className="mt-3 flex items-center gap-2 text-sm text-[#625e61]"><i className={cn("size-2 rounded-full", tone === "success" ? "bg-emerald-700" : "bg-amber-400")} />{label}</span></div>; }
function LoadDistribution({ selectedTarget }: { selectedTarget: string }) { const ws105Active = selectedTarget === "WS-105"; return <section className="flex min-h-[460px] flex-col rounded-[2rem] border border-[#ddd6ce] bg-white p-7 shadow-[0_22px_40px_rgba(0,0,0,0.035)]"><div><h2 className="text-xl font-semibold">Load Distribution Shift</h2><p className="mt-1 text-sm text-[#625e61]">Comparing current state vs proposed rerouting</p></div><div className="mt-auto space-y-8"><LoadBar label="WS-102 (Current)" current="85% capacity" proposed="Dropping to 0% load" currentWidth="85%" proposedWidth="0%" tone="danger" /><LoadBar label={`WS-105 (Proposed for J1001${ws105Active ? ", J1002" : ""})`} current="Current: 45%" proposed={ws105Active ? "Proposed: 80%" : "Proposed: 45%"} currentWidth="45%" proposedWidth={ws105Active ? "80%" : "45%"} tone="warning" /><LoadBar label="WS-108 (Proposed for J1003)" current="Current: 20%" proposed="Proposed: 60%" currentWidth="20%" proposedWidth="60%" tone="info" /></div></section>; }
function LoadBar({ label, current, proposed, currentWidth, proposedWidth, tone }: { label: string; current: string; proposed: string; currentWidth: string; proposedWidth: string; tone: "danger" | "warning" | "info" }) { const color = tone === "danger" ? "bg-[#ffb5b0]" : tone === "warning" ? "bg-amber-400" : "bg-[#4968ef]"; return <div><div className="flex justify-between gap-3 text-sm"><strong>{label}</strong><span className={tone === "danger" ? "text-[#ba1a1a]" : tone === "warning" ? "text-amber-600" : "text-[#4968ef]"}>{proposed}</span></div><div className="relative mt-3 h-4 overflow-hidden rounded-full bg-[#e9e5e1]"><div className={cn("absolute inset-y-0 left-0", tone === "danger" ? color : "bg-black")} style={{ width: currentWidth }} /><div className={cn("absolute inset-y-0 left-0 opacity-90", color)} style={{ width: proposedWidth }} /></div><div className="mt-2 flex justify-between text-[10px] font-semibold tracking-[0.06em] text-[#696468]"><span>{current}</span><span>{proposed}</span></div></div>; }
