"use client";
import { useEffect, useRef, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { CirclePause, CirclePlay, MousePointer2, RotateCcw, X } from "lucide-react";
import { getStorySteps } from "@/components/story/scenario";
import { useOperations, type DemoScenarioId, type StoryMode } from "@/contexts/OperationsContext";

type StartDetail = { scenario: DemoScenarioId; mode: StoryMode };
const wait = (duration: number) => new Promise((resolve) => window.setTimeout(resolve, duration));

export function StoryModeController() {
  const router = useRouter(); const pathname = usePathname(); const operations = useOperations(); const latest = useRef(operations); latest.current = operations;
  const [active, setActive] = useState(false); const [index, setIndex] = useState(0); const [paused, setPaused] = useState(false); const [running, setRunning] = useState(false); const [failure, setFailure] = useState<string | null>(null); const [cursor, setCursor] = useState({ x: 48, y: 48, visible: false });
  const steps = getStorySteps(operations.demoScenario); const step = steps[index];
  useEffect(() => { const listener = async (event: Event) => { const detail = (event as CustomEvent<StartDetail>).detail; setFailure(null); setIndex(0); setPaused(false); setActive(true); const ready = await latest.current.enterDemo(detail.scenario, detail.mode); if (!ready) { setFailure(latest.current.backendError ?? "Demo runtime could not be prepared."); setPaused(true); } }; window.addEventListener("manufacture-flow:start-story", listener); return () => window.removeEventListener("manufacture-flow:start-story", listener); }, []);
  const evidenceMet = (kind: typeof step.evidence) => { const snapshot = latest.current.activeCase; const workOrder = snapshot?.maintenanceWorkOrders[0]; if (!kind) return true; if (kind === "graph") return Boolean(snapshot && workOrder); if (kind === "stage3") return Boolean(workOrder && workOrder.stage >= 3); if (kind === "stage4") return workOrder?.stage === 4; if (kind === "stage5") return workOrder?.stage === 5; if (kind === "failed") return Boolean(snapshot?.events.some((event) => event.eventType === "return_to_service_validation_failed") && snapshot.allocationLocks.some((lock) => lock.state === "active")); return Boolean(snapshot?.failureCase.workflowState.toLowerCase().includes("recovered") && snapshot.allocationLocks.every((lock) => lock.state === "released")); };
  const waitForEvidence = async (kind: typeof step.evidence, timeout = 35_000) => { const started = Date.now(); while (!evidenceMet(kind)) { if (Date.now() - started > timeout) throw new Error(`Timed out waiting for persisted ${kind} state.`); await latest.current.refresh(); await wait(450); } };
  const locate = async (selector: string) => { const started = Date.now(); while (Date.now() - started < 12_000) { const element = document.querySelector<HTMLElement>(selector); if (element) return element; await wait(120); } throw new Error(`Tour target not found: ${selector}`); };
  const act = async (action: typeof step.action, element: HTMLElement) => { if (!action) return; element.click(); await waitForEvidence(step.evidence); };
  const runStep = async () => { if (!step || running || paused) return; setRunning(true); setFailure(null); try { if (pathname !== step.route) { router.push(step.route); await wait(350); } const target = await locate(step.target); target.scrollIntoView({ behavior: operations.state.reducedMotion ? "auto" : "smooth", block: "center" }); const box = target.getBoundingClientRect(); setCursor({ x: box.left + box.width / 2, y: box.top + box.height / 2, visible: true }); await wait(operations.state.reducedMotion ? 50 : 650); if (operations.storyMode === "manual" && step.action) await waitForEvidence(step.evidence); else { await act(step.action, target); if (!step.action) await waitForEvidence(step.evidence); } await wait(500); if (index === steps.length - 1) setPaused(true); else setIndex((value) => value + 1); } catch (error) { setFailure(error instanceof Error ? error.message : "Story step failed."); setPaused(true); } finally { setRunning(false); } };
  useEffect(() => { if (active && operations.storyMode === "auto" && !paused && !running) void runStep(); }, [active, index, operations.storyMode, paused, pathname, running]);
  if (!active || !step) return null;
  const exit = async () => { setActive(false); setCursor((value) => ({ ...value, visible: false })); await operations.exitDemo(); router.push("/dashboard"); };
  return <><button data-tour-id="trigger-telemetry" onClick={() => void operations.triggerDemo()} className="fixed bottom-5 right-5 z-[68] min-h-11 rounded-full bg-amber-300 px-4 text-xs font-bold text-black shadow-xl">Trigger controlled telemetry</button>{cursor.visible ? <div aria-hidden className="pointer-events-none fixed z-[80] transition-[left,top] duration-500" style={{ left: cursor.x, top: cursor.y, transform: "translate(-5px,-4px)" }}><MousePointer2 className="size-8 fill-white text-black drop-shadow-lg" /></div> : null}<aside role="dialog" aria-label="Story Mode controller" className="fixed bottom-5 left-1/2 z-[75] w-[min(94vw,720px)] -translate-x-1/2 rounded-[1.5rem] border border-white/10 bg-[#211f1e]/95 p-4 text-white shadow-[0_30px_90px_rgba(0,0,0,0.42)] backdrop-blur"><div className="flex items-start gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-amber-300 font-mono text-sm font-bold text-black">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-bold tracking-[0.14em] text-amber-300">DEMO SANDBOX · {operations.storyMode.toUpperCase()}</span><span className="text-[10px] text-white/50">{index + 1} / {steps.length}</span></div><h2 className="mt-1 text-lg font-semibold">{step.title}</h2><p className="mt-1 text-sm leading-5 text-white/65">{operations.storyMode === "manual" ? step.manualInstruction : step.explanation}</p>{failure ? <p role="alert" className="mt-2 rounded-lg bg-red-400/15 px-3 py-2 text-xs text-red-200">{failure}</p> : null}</div><button onClick={() => void exit()} aria-label="Exit Demo" className="grid size-10 shrink-0 place-items-center rounded-full hover:bg-white/10"><X className="size-4" /></button></div><div className="mt-4 flex flex-wrap items-center gap-2 border-t border-white/10 pt-3"><button onClick={() => setPaused((value) => !value)} className="inline-flex min-h-10 items-center gap-2 rounded-full bg-white/10 px-4 text-xs font-semibold">{paused ? <CirclePlay className="size-4" /> : <CirclePause className="size-4" />}{paused ? "Resume" : "Pause"}</button>{operations.storyMode === "manual" ? <button disabled={running} onClick={() => void runStep()} className="min-h-10 rounded-full bg-amber-300 px-4 text-xs font-bold text-black disabled:opacity-50">{running ? "Waiting for persisted state…" : step.action ? "Perform highlighted action" : "Continue"}</button> : null}<button onClick={async () => { setPaused(true); if (await operations.resetDemo()) { setIndex(0); setFailure(null); setPaused(false); router.push("/dashboard"); } }} className="ml-auto inline-flex min-h-10 items-center gap-2 rounded-full px-3 text-xs font-semibold text-white/70 hover:bg-white/10"><RotateCcw className="size-4" />Restart</button></div></aside></>;
}
