"use client";
import { useState } from "react";
import { Bot, Play, RotateCcw, UserRound } from "lucide-react";
import { useOperations, type DemoScenarioId, type StoryMode } from "@/contexts/OperationsContext";

export function StoryLauncher() {
  const { runtime, runtimeBusy, resetDemo, exitDemo } = useOperations(); const [open, setOpen] = useState(false); const [mode, setMode] = useState<StoryMode>("auto"); const [scenario, setScenario] = useState<DemoScenarioId>("golden");
  const start = () => { window.dispatchEvent(new CustomEvent("manufacture-flow:start-story", { detail: { mode, scenario } })); setOpen(false); };
  return <div className="relative" data-tour-id="story-launcher"><button onClick={() => setOpen((value) => !value)} className="inline-flex min-h-12 cursor-pointer items-center gap-2 rounded-full bg-[#252423] px-5 text-sm font-semibold text-white shadow-md transition-colors hover:bg-black focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-black"><Play className="size-4" />Story / Demo Mode</button>{open ? <section className="absolute right-0 top-14 z-40 w-[min(92vw,390px)] rounded-[1.5rem] border border-black/10 bg-white p-5 text-left shadow-[0_24px_70px_rgba(0,0,0,0.22)]"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold tracking-[0.14em] text-amber-700">PRESENTATION SANDBOX</p><h2 className="mt-1 text-xl font-semibold">Start a persisted scenario</h2></div>{runtime === "demo" ? <span className="rounded-full bg-amber-100 px-3 py-1 text-[10px] font-bold text-amber-900">DEMO SANDBOX</span> : null}</div><fieldset className="mt-5"><legend className="text-xs font-semibold">Mode</legend><div className="mt-2 grid grid-cols-2 gap-2">{(["manual", "auto"] as StoryMode[]).map((item) => <button key={item} onClick={() => setMode(item)} className={`min-h-11 rounded-xl border px-3 text-sm font-semibold ${mode === item ? "border-black bg-black text-white" : "border-black/10 bg-white"}`}>{item === "auto" ? <Bot className="mr-2 inline size-4" /> : <UserRound className="mr-2 inline size-4" />}{item === "auto" ? "Auto" : "Manual"}</button>)}</div></fieldset><label className="mt-4 block text-xs font-semibold">Scenario<select value={scenario} onChange={(event) => setScenario(event.target.value as DemoScenarioId)} className="mt-2 h-11 w-full rounded-xl border border-black/15 bg-white px-3 text-sm"><option value="golden">Golden Complete Recovery</option><option value="local-spare">Local Spare Available</option><option value="failure-rework">Failure / Rework</option></select></label><div className="mt-5 grid grid-cols-2 gap-2"><button disabled={runtimeBusy} onClick={start} className="min-h-11 rounded-xl bg-black px-4 text-sm font-semibold text-white disabled:opacity-50">{runtimeBusy ? "Preparing…" : "Start"}</button><button disabled={runtimeBusy || runtime !== "demo"} onClick={() => void resetDemo(scenario)} className="min-h-11 rounded-xl border border-black/15 px-4 text-sm font-semibold disabled:opacity-40"><RotateCcw className="mr-2 inline size-4" />Reset Demo</button></div>{runtime === "demo" ? <button onClick={() => void exitDemo()} className="mt-2 min-h-10 w-full text-xs font-semibold text-red-700">Exit Demo and restore Live</button> : null}</section> : null}</div>;
}
